# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: myapp
# data:
#   hello: raza
#   AWS_SECRET: jfd
#   PORT: "3000"

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: <Password>
