apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: myapp
          resources:
            requests:
              memory: "50Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  hello: raza
  AWS_SECRET: jfd
  PORT: "3000"
