apiVersion: apps/v1
kind: Deployment
metadata:
  name: init
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

      initContainers:
        - name: busybox-container
          image: busybox:latest
          command: ["sh", "-c"]
          args:
            - "echo Init container started; sleep 5"
