apiVersion: v1
kind: Pod
metadata:
  name: nginx-new-pod
  labels:
    app.kubernetes.io/name: nginx-new-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
