# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: myreplicaset
#   labels:
#     app: myapp
#     key: value
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       key: value
#   template:
#     metadata:
#       labels:
#         key: value
#     spec:
#       containers:
#         - name: nginx-container
#           image: nginx-latest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deploy
#   labels:
#     env: demo
# spec:
#   template:
#     metadata:
#       labels:
#         env: demo
#       name: nginx
#     spec:
#       containers:
#         - image: nginx:latest
#           name: nginx
#           ports:
#             - containerPort: 80
#   replicas: 3
#   selector:
#     matchLabels:
#       env: demo

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deploy
#   labels:
#     env: demo
# spec:
#   template:
#     metadata:
#       labels:
#         env: demo
#       name: nginx
#     spec:
#       containers:
#         - image: nginx:latest
#           name: nginx
#           ports:
#             - containerPort: 80
#   replicas: 3
#   selector:
#     matchLabels:
#       env: demo
