apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "490m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-volume-storage
              mountPath: /data/redis
      volumes:
        - name: redis-volume-storage
          persistentVolumeClaim:
            claimName: mypvc
      nodeName: cluster-worker
