apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deplo
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
